openapi: 3.0.3
info:
  title: 'Evaluacion de conocimientos Laravel Fabián Coronel'
  description: 'Esta es una API Rest que se encarga del manejo de peliculas previamente descargados de una base de datos en linea'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/peliculas:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  peliculas:
                    -
                      id: 3
                      created_at: '2025-02-06T16:16:19.000000Z'
                      updated_at: '2025-02-06T20:35:35.000000Z'
                      titulo: 'Los 7 magnificos'
                      descripcion: Oeste
                    -
                      id: 4
                      created_at: '2025-02-06T16:17:49.000000Z'
                      updated_at: '2025-02-06T16:17:49.000000Z'
                      titulo: Hola
                      descripcion: Hola
                    -
                      id: 5
                      created_at: '2025-02-06T16:18:07.000000Z'
                      updated_at: '2025-02-06T16:18:07.000000Z'
                      titulo: Hola
                      descripcion: Hola
                    -
                      id: 6
                      created_at: '2025-02-06T16:18:50.000000Z'
                      updated_at: '2025-02-06T16:18:50.000000Z'
                      titulo: Hola
                      descripcion: Hola
                    -
                      id: 7
                      created_at: '2025-02-06T16:19:51.000000Z'
                      updated_at: '2025-02-06T16:19:51.000000Z'
                      titulo: Hola
                      descripcion: Hola
                properties:
                  status:
                    type: boolean
                    example: true
                  peliculas:
                    type: array
                    example:
                      -
                        id: 3
                        created_at: '2025-02-06T16:16:19.000000Z'
                        updated_at: '2025-02-06T20:35:35.000000Z'
                        titulo: 'Los 7 magnificos'
                        descripcion: Oeste
                      -
                        id: 4
                        created_at: '2025-02-06T16:17:49.000000Z'
                        updated_at: '2025-02-06T16:17:49.000000Z'
                        titulo: Hola
                        descripcion: Hola
                      -
                        id: 5
                        created_at: '2025-02-06T16:18:07.000000Z'
                        updated_at: '2025-02-06T16:18:07.000000Z'
                        titulo: Hola
                        descripcion: Hola
                      -
                        id: 6
                        created_at: '2025-02-06T16:18:50.000000Z'
                        updated_at: '2025-02-06T16:18:50.000000Z'
                        titulo: Hola
                        descripcion: Hola
                      -
                        id: 7
                        created_at: '2025-02-06T16:19:51.000000Z'
                        updated_at: '2025-02-06T16:19:51.000000Z'
                        titulo: Hola
                        descripcion: Hola
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 3
                        created_at:
                          type: string
                          example: '2025-02-06T16:16:19.000000Z'
                        updated_at:
                          type: string
                          example: '2025-02-06T20:35:35.000000Z'
                        titulo:
                          type: string
                          example: 'Los 7 magnificos'
                        descripcion:
                          type: string
                          example: Oeste
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/peliculas/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 3
                  created_at: '2025-02-06T16:16:19.000000Z'
                  updated_at: '2025-02-06T20:35:35.000000Z'
                  titulo: 'Los 7 magnificos'
                  descripcion: Oeste
                properties:
                  id:
                    type: integer
                    example: 3
                  created_at:
                    type: string
                    example: '2025-02-06T16:16:19.000000Z'
                  updated_at:
                    type: string
                    example: '2025-02-06T20:35:35.000000Z'
                  titulo:
                    type: string
                    example: 'Los 7 magnificos'
                  descripcion:
                    type: string
                    example: Oeste
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the pelicula.'
        example: 3
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
